forms/QuestionForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, BooleanField, validators


class QuestionForm(FlaskForm):
    content = StringField('질문 입력', validators=[validators.DataRequired()])
    order_num = IntegerField('질문 번호', validators=[validators.DataRequired()])
    is_active = BooleanField('활성화')
    submit = SubmitField('추가')

views/question_views.py
from flask import Blueprint, render_template, flash, redirect, url_for, session
from flask import request

from forms.Answerform import AnswerForm
from models.model_definitions import AnswerModel
from views.question_util.utils import (
    get_session_info,
    verify_question_order_num,
    insert_answer_in_database,
    get_form_data,
    redirect_next_question
)

question_blp = Blueprint('QUESTION', __name__, url_prefix='/questions')


@question_blp.route('/result', methods=['GET'])
def question_result():
    session_info = get_session_info()
    flash('검사 완료', category="success")
    session.pop('user_id', None)
    answers = AnswerModel.query.filter_by(user_id=session_info['answered_user_id']).order_by(
        AnswerModel.id.asc()).all()
    return render_template(
        'question/result.html',
        answered_user=session_info['answered_username'],
        answers=answers
    )


@question_blp.route('/detail/<int:question_order_num>/', methods=['GET', 'POST'])
def question_detail(question_order_num):
    # get session info to verify the current user is valid
    session_info = get_session_info()
    # if there is no session info, redirect to user_info page
    if not session_info['answered_username']:
        flash("Please enter your information", category="error")
        return redirect(url_for('MAIN.user_info'))

    # get question if question order number less than true state question numbers
    question = verify_question_order_num(question_order_num)
    answer_form = AnswerForm(request.form)
    if question:
        if request.method == 'POST' and answer_form.validate_on_submit():
            if insert_answer_in_database(get_form_data(answer_form), session_info, question.id):
                return redirect_next_question(question_order_num, session_info)

    # if request.method == 'GET', just render question_detail page
    return render_template(
        'question/question_detail.html',
        question_order_num=question_order_num,
        question=question,
        form=answer_form
    )

templates/question/question_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-5">
    <h1 class="mb-4 text-center">Question {{ question_order_num }}</h1>
    <div class="card shadow-lg">
        <div class="card-body text-center">
            <h5 class="card-title">{{ question.content }}</h5>
        </div>
        <div class="card-footer">
            <form id="question_form" action="{{ url_for('QUESTION.question_detail', question_order_num=question_order_num) }}" method="post">
                {{ form.hidden_tag() }}
                <div class="mb-3">
                    {{ form.answer.label(class="form-label") }}
                    {{ form.answer(class="form-radio") }}
                </div>
                <div class="d-grid gap-2">
                    {{ form.submit(class="btn btn-primary btn-lg") }}
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/question/result.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-4">
    <h1 class="mb-4">{{ answered_user }} 님이 응답한 결과는...</h1>
    {% if answers %}
        <div class="list-group">
            {% for answer in answers %}
                <div class="list-group-item">
                <!--- Will be modified UI when there is a chance to improved in the future...-->
                    <h5 class="mb-1">Answer ID: {{ answer.id }}</h5>
                    <p class="mb-1">Answered User: {{ answer.user_id }}</p>
                    <p class="mb-1">Answer Question: {{ answer.question_id }}</p>
                    <p class="mb-1">Answer Response: {{ answer.chosen_answer }}</p>
                </div>
                {% if not loop.last %}
                    <hr>
                {% endif %}
            {% endfor %}
        </div>
    {% else %}
        <p class="mb-1">표시할 답변이 존재하지 않습니다.</p>
    {% endif %}
    <form action="{{ url_for('MAIN.index') }}" method="get">
        <button class="btn btn-primary">처음으로 되돌아가기</button>
    </form>
</div>
{% endblock %}